### ISSUE TITLE
Person node: internal automatic check to prevent duplicates

### ISSUE THREAD

**Issue by doricon** [paleobot/pbot-dev#181] opened 2023-08-02 19:55 UTC
We need to have an internal check on person node so that when you submit the system prevents, or warns, about duplicate name. 

We can't delete people nodes, so we need to have good stop for duplicating people.

**Comment by aazaff** [comment] 2023-08-03 14:41
Duplicate of #100

**Closed by aazaff** 2023-08-03 14:41 UTC
