### ISSUE TITLE
Can't delete group "PBot Leaf Anatomy Working Group" due to blocking relationships

### ISSUE THREAD

**Issue by clairecleveland** [paleobot/pbot-dev#177] opened 2023-08-02 19:34 UTC
Trying to delete this but appears to be linked to something. We can't figure out what it is linked to because all of the old data it could have been linked to was deleted. Double checked the things just entered and no links there.

**Comment by NoisyFlowers** [comment] 2023-08-02 22:31
That Group still has five members. MEMBER_OF is a blocking relationship. This in itself is by design and not a bug. It can also be changed.

There is a bug, however. You can only remove four of the members via Group edit. The fifth, the person doing the editing, cannot be removed. Thus, the Group, or any Group really, can not be deleted. 

Any fix for this will be too hairy to tackle until after Hackathon

**Comment by clairecleveland** [comment] 2023-08-02 22:49
Yes we tried removing all the members allowed and deleting it, but as you
said we can’t delete the creator so it failed. I don’t think it will cause
issues next week. Hopefully people will only create one or two truly needed
groups each.

**Comment by NoisyFlowers** [comment] 2024-02-02 23:04
This was fixed in paleobot/pbot-api@6245cf053b26ef12ccbc69d4c13b83b6cdf40228, back in late August. 

Please verify that you can delete that group and I'll close this

**Closed** 2024-08-29 17:29 UTC
Labels: bug, low priority
