### ISSUE TITLE
Description allows specimens to be described by the same schema more than once.

### ISSUE THREAD

**Issue by clairecleveland** [paleobot/pbot-dev#170] opened 2023-08-02 14:53 UTC
Not sure this absolutely needs to be fixed before Hack-A-Thon since it might be complicated. We could instruct around it if needed, I think.

I was able to create a description for Hack-A-Thon Specimen 230808.CC.1. 

Then I was able to create simultaneous descriptions for specimens: Hack-A-Thon Specimen 230808.CC.2 and Hack-A-Thon Specimen 230808.CC.1.

**Comment by doricon** [comment] 2023-08-02 15:10
I don't see what the problem is... we do want specimens to be able to have multiple descriptions. Say for example, one author describes a specimen in 1903, and later it is redescribed in 2023 by another worker and with newer interpretation of the features. Both cases can be described by the MLA, but the descriptions may differ. The two descriptions with the MLA record the history of the specimen's descriptions (and publications). 

Mostly, I think this will be important to consider in how we display information for specimens and otus that have multiple description nodes.

**Comment by clairecleveland** [comment] 2023-08-02 15:21
Oy, don't like the idea that descriptions using the same schema would result in different outcomes through different users. To me that says they are badly defined schemas.

**Comment by doricon** [comment] 2023-08-02 15:30
lol I hear ya. An unfortunate reality is that even with the best designed schema possible, there will be differences based on who is interpreting the fossil. I've updated/redescribed my own specimens 3-5 years later and the description has been different because I have honed my skills at interpreting venation, or realized I was misunderstanding a feature (total user error, the definitions in the schema were fine). Rather than delete my original description in my private workbench, I would want to enter my updated description, then compare and consider them to check for things I've missed or need to look at more. And then delete the out-of-date one before going public. In which case, being able to have two MLA descriptions for a specimen is really useful for my workflow.

**Comment by aazaff** [comment] 2023-08-02 15:59
Regardless, going back to Claire's original post. Absolutely nothing, no matter how dire will be fixed anymore before the hackathon. We are now freezed for further bug fixes or enhancement until after the meeting.

**Comment by ecurrano** [comment] 2023-09-01 20:31
From a botany standpoint, we probably want to educate on this, and also think over the implications of Andrew's comment: currently when we select an OTU and grab the description from the holotype, what would we do if the holotype has more than one description.

**Comment by aazaff** [comment] 2024-08-06 20:53
@ecurrano can we close this one now?

**Comment by ecurrano** [comment] 2024-08-06 20:58
I believe so. Dori and I have been working on a best practices document that will educate users on how to name the different descriptions and what to write in the notes field. We may still need to think about how we want descriptions displayed on specimen or OTU pages, but there's not anything especially ground-breaking here with regards to that discussion.

**Closed by ecurrano** 2024-08-06 20:58 UTC
Labels: question
