### ISSUE TITLE
Person search in reference not working

### ISSUE THREAD

**Issue by ecurrano** [paleobot/pbot-dev#179] opened 2023-08-02 19:38 UTC
I am trying to add authors to a reference. When I click the magnifying glass to search for people nodes, I am not getting search results for people I recently entered. For example, when searching by surname, I can find Andrew Flynn, but I cannot find William C Clyde.

Let me know if you need more information on this.

**Comment by ecurrano** [comment] 2023-08-02 19:41
I also had this issue when trying to search for a person in the people node.

**Comment by NoisyFlowers** [comment] 2023-08-02 22:37
To be clear: you're saying that you enter a person, then, when you try to add another, you are not seeing that previous person in the list of people you can select from. Is this correct?

If so, that is by design. This is how the client-side logic prevents duplicate authors/people.

**Comment by ecurrano** [comment] 2023-08-02 22:56
No. For example, I entered William C Clyde today. I want to add him as an author on a Journal Article. I can see him on the dropdown menu, but if I try hitting the magnifying glass and searching under surname Clyde (or given name William), I get no results. In contrast, if I search given name for Andrew, I get Andrew Flynn and two Andrew Zaffos. 

The same problem occurs when I am in explore and searching person nodes for William or Clyde.

**Comment by aazaff** [comment] 2023-08-02 23:12
I think I follow, but just for clarity can you include screenshots.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

From: Ellen ***@***.***>
Sent: Wednesday, August 2, 2023 3:57 PM
To: ***@***.***>
Cc: Zaffos, Andrew - ***@***.***>; ***@***.***>
Subject: [EXT]Re: [paleobot/pbot-dev] Person search in reference not working (Issue #179)


External Email

No. For example, I entered William C Clyde today. I want to add him as an author on a Journal Article. I can see him on the dropdown menu, but if I try hitting the magnifying glass and searching under surname Clyde (or given name William), I get no results. In contrast, if I search given name for Andrew, I get Andrew Flynn and two Andrew Zaffos.

The same problem occurs when I am in explore and searching person nodes for William or Clyde.

**Comment by ecurrano** [comment] 2023-08-02 23:15
I'm entering a reference:
<img width="790" alt="Screen Shot 2023-08-02 at 5 14 07 PM" src="https://github.com/paleobot/pbot-dev/assets/72828382/25358bca-4dc1-455c-aecf-87902b1ca172">
I try to search for Clyde:
<img width="583" alt="Screen Shot 2023-08-02 at 5 14 18 PM" src="https://github.com/paleobot/pbot-dev/assets/72828382/12343401-963f-456a-8d0c-502bc60a5d24">
My results:
<img width="595" alt="Screen Shot 2023-08-02 at 5 14 25 PM" src="https://github.com/paleobot/pbot-dev/assets/72828382/6a57965e-0f9f-498d-84c4-a633711f9337">

**Comment by ecurrano** [comment] 2023-08-02 23:16
And here's the dropdown menu showing that William C Clyde is there
<img width="671" alt="Screen Shot 2023-08-02 at 5 15 57 PM" src="https://github.com/paleobot/pbot-dev/assets/72828382/5099bddd-8b22-4a64-9a53-0a5c58f5ed65">

**Comment by ecurrano** [comment] 2023-08-02 23:17
If I search for Andrew instead:
<img width="577" alt="Screen Shot 2023-08-02 at 5 16 44 PM" src="https://github.com/paleobot/pbot-dev/assets/72828382/f51057e6-8ba7-4116-b062-7b0a6cd16011">
I get this result:
<img width="589" alt="Screen Shot 2023-08-02 at 5 16 50 PM" src="https://github.com/paleobot/pbot-dev/assets/72828382/fe7fabeb-cef1-4cc9-a7c4-a5dccd16ed9f">

**Comment by ecurrano** [comment] 2023-08-02 23:18
And here's what I got when I searched for Clyde (same as in search above) in Explore:
<img width="234" alt="Screen Shot 2023-08-02 at 5 17 41 PM" src="https://github.com/paleobot/pbot-dev/assets/72828382/8c3f2f39-c18d-4944-a6a1-918f7888fd94">

**Comment by NoisyFlowers** [comment] 2023-08-03 00:08
Poor Mr. Clyde was created without a Group. 

Person nodes are supposed to be created automatically as public. I've corrected the logic failed Mr. Clyde. This is in:
paleobot/pbot-api@e846cf097e68bbc057d31a978dafdfb39054d5c4
paleobot/pbot-client@3b19b9e6b5f24f507486a3f61f938d79813a8d24 

I also manually added Mr. Clyde to public.

Please close if it works for you

**Comment by ecurrano** [comment] 2023-08-03 01:08
Works for Mr. Clyde. Could you please also fix: Robert Buchwaldt, Esther RS Pinheiro, and Ian M Miller. @doricon  also added some new people today that will need to be fixed.

**Comment by NoisyFlowers** [comment] 2023-08-03 01:23
I've created MEMBER_OF relationships to public for all Person nodes that were not already.

**Comment by doricon** [comment] 2023-08-03 13:58
Fabulous, mine work too now. I am closing this.

**Closed by doricon** 2023-08-03 13:58 UTC
Labels: bug, high priority, Hack-A-Thon
